cabal-version:       3.0
name:                waymonad-scanner
version:             0.1.0.0
-- synopsis:
-- description:
license:             LGPL-2.1-or-later
license-file:        LICENSE
author:              Markus Ongyerth
maintainer:          abab9579@gmail.com
-- copyright:
category:            System
build-type:          Simple
extra-source-files:  ChangeLog.md

library
  -- Modules exported by the library.
  exposed-modules:
    Graphics.Wayland.Scanner
    Graphics.Wayland.Scanner.Dispatcher
    Graphics.Wayland.Scanner.Marshal
    Graphics.Wayland.Scanner.Types
    Graphics.Wayland.Scanner.WLS
    Graphics.Wayland.Scanner.XML
  other-modules:
    Graphics.Wayland.Util.Types
    Graphics.Wayland.Server.Resource
    Utility
  default-extensions:
    LambdaCase
    NoFieldSelectors
    OverloadedRecordDot
  build-depends:
    base >=4.15 && <5,
    mtl,
    containers,
    cereal,
    text,
    bytestring,
    process,
    template-haskell >=2.16,
    xml >=1.3 && <1.4,
  build-tool-depends:
    c2hs:c2hs >=0.28,
  pkgconfig-depends:
    wayland-server,
  hs-source-dirs:      src
  default-language:    GHC2021
  ghc-options:         -Wall
